### PR TITLE
Restore missing None check for focused window

### LINKED ISSUE #52: inactive-window-transparency stops working
I upgraded a day or two ago and found my inactive windows no longer transparent after a while. I haven't yet narrowed down what causes this. I suspected swayidle putting the monitor to sleep, but switching back and forth on a KVM didn't trigger it, and it just happened again a few minutes after restarting sway.

Error transcribed from output post-exit:

```
'NoneType' object has no attribute 'workspace'
Traceback (most recent call last):
  File "/usr/share/sway-contrib/inactive-windows-transparency.py", line 88, in <module>
    ipc.main()

  File "/usr/lib/python3.13/site-packages/i3ipc/connection.py", line 514, in main
    raise loop_exception
  File "/usr/lib/python3.13/site-packages/i3ipc/connection.py", line 497, in main
    while not self._event_socket_pull():

00:00:00.000 [common/ipc-client.c:66] Unable to connect to /run/user/1000/sway-ipc.1000.1221.socket
```

### PR DESCRIPTION
**Pull request by chamlis**
I broke this in 619783a (sorry about that!).

Closes #52

### CODE REVIEW

**Review by dmfay — APPROVED** [review]
I applied locally & so far so good!

**Review by OctopusET — APPROVED** [review]
LGTM
